version: '3.13'

services:
  db:
    image: postgres:17
    container_name: car_postgres
    restart: always
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  app:
    build: .
    stdin_open: true  # فعال کردن stdin
    tty: true         # اختصاص یک ترمینال مجازی
    depends_on:
      - db
    environment:
      DB_NAME: car_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

volumes:
  db-data:
